### ISSUE TITLE
Extra case to handle for makeLink()

### ISSUE THREAD

**Issue by shiondev** [datafiniti/EightyApps#2]
If I use the LinkCollector 80app on http://davyweb.net/ont/, I get:

{
links : [
http://davyweb.net/?C=N;O=D,
http://davyweb.net/?C=M;O=A,
http://davyweb.net/?C=S;O=A,
http://davyweb.net/?C=D;O=A,
http://davyweb.net/,
http://Action.owl,
http://ActionHistory.owl,
http://ActionStatus.owl,
...
and so on

Those last three links should include davyweb.net/ in them as well.  The makeLink 80app is not handling this:

href="Action.owl"

**Comment by hessmjr** [comment]
@shiondev @mistermoe haha is this still an issue?

**Comment by shiondev** [comment]
We are robots blocked on this website now.. lol

**Comment by hessmjr** [comment]
Guess we can close this then.
