### ISSUE TITLE
How to execute asynchronous actions

### ISSUE THREAD

**Issue by lbineau** [datafiniti/EightyApps#6]
Hi,

How can I execute asynchronous actions (click, ajax, call, ...) before collecting the data ?
On the page I want to crawl the data are refreshed with Ajax without refreshing URL.

Thanks.

**Comment by shiondev** [comment]
Hi there - I responded on your support ticket, but just to answer here as well:

Running async calls from the 80app is currently not available. We have experimented some on how to do this, but aren't ready to release it to our users (there's a lot of potential for misusing it).
